name: Feature request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: A clear and concise description of what feature is currently missing. What issues are you currently running into?
      placeholder: "Currently I'm missing a specialized column type for storing email addresses."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
      placeholder: |
        A new ColumnType for email addresses with propper support for related functionalities:
        - Clickable links with 'mailto:' in the table view
        - <mailto:my@example.com> in RDF API
        - etc.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Using String to store the data instead."
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "If not implemented, RDF API will need a specific solution instead to ensure support for `mailto:`."